### PR TITLE
[WIP] Upgrade SDK project to Angular and RxJs 6

### PR DESCRIPTION
**Pull request by RSuter**
Upgrade to latest NSwag and upgrade to Angular 6 and RxJs 6

- [ ] Test UI locally
- [ ] Test tree-shaking

See also https://github.com/RSuter/NSwag/issues/1255

### CODE REVIEW

**Comment by neotek** [comment]
@RSuter AppVeyor build failed.

**Comment by RSuter** [comment]
It seems that AppVeyer uses an unsupported NodeJS version: 

> You are running version v6.14.2 of Node.js, which is not supported by Angular CLI v6.
1638

**Comment by RSuter** [comment]
Looks good now: https://ci.appveyor.com/project/Picturepark/picturepark-sdk-typescript-hgo7c/build/414

**Comment by RSuter** [comment]
Looks good now...

**Pull request merged**
