### PR TITLE
Use VideoJS

### PR DESCRIPTION
**Pull request by RSuter**
Working version with some UI issues. 

**ToDos:**

- [x] Fix UI styles
- [x] Embed VideoJS CSS (dynamically load css styles, do not add in templates)

Share token for a shared list can be obtained like this: 

image

### CODE REVIEW

**Comment by RSuter** [comment]
@cguedel thanks for testing. Will look into this soon...

**Comment by neotek** [comment]
In the gallery template, when opening a video (in photoswipe) and then close the overlay, the video continues to play and is not destroyed.

**Comment by neotek** [comment]
> In the gallery template, when opening a video (in photoswipe) and then close the overlay, the video continues to play and is not destroyed.

@RSuter Could you check this?

**Comment by RSuter** [comment]
> In the gallery template, when opening a video (in photoswipe) and then close the overlay, the video continues to play and is not destroyed.

Fixed.

**Pull request merged**
